Fix cleanup job in pipeline

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -394,41 +394,68 @@ jobs:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
       - revert-migrations:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-
   cleanup:
     docker:
       - image: amazon/aws-cli
     steps:
       - checkout
       - run:
-          name: install dependencies
+          name: Get old stack workflow id
           command: |
-            yum -y install tar
-            yum -y install gzip
-      - attach_workspace:
-          at: ~/
-      - run:
-          name: Get OldWorkflowID
-          command: |
-            export OldWorkflowID=$(cat .circleci/files/OldWorkflowID.txt)
-            echo $OldWorkflowID
-            export STACKS=$(aws cloudformation list-stacks \
-            --query "StackSummaries[*].StackName" \
-            --stack-status-filter CREATE_COMPLETE --no-paginate --output text)
-            echo Stack names: "${STACKS[@]}"
+            # Fetch the Old workflow ID
+            export OldWorkflowID=$(aws cloudformation \
+                    list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+                    --no-paginate --output text)
+            echo OldWorkflowID: "${OldWorkflowID}"
+            echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
+            # Fetch the stack names          
+            export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
+                    --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
+            echo Stack names: "${STACKS[@]}"  
       - run:
           name: Remove old stacks and files
           command: |
-            export OldWorkflowID=$(cat .circleci/files/OldWorkflowID.txt)
-            if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "${OldWorkflowID}" ]]
+            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
             then
               echo "--Delete confirmed--"
               aws s3 rm "s3://$udapeople-{OldWorkflowID}" --recursive ||true
               aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}" ||true
               aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}" ||true
-            else
-              echo --------cannot remove stacks ---------
             fi
+  # cleanup:
+  #   docker:
+  #     - image: amazon/aws-cli
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: install dependencies
+  #         command: |
+  #           yum -y install tar
+  #           yum -y install gzip
+  #     - attach_workspace:
+  #         at: ~/
+  #     - run:
+  #         name: Get OldWorkflowID
+  #         command: |
+  #           export OldWorkflowID=$(cat .circleci/files/OldWorkflowID.txt)
+  #           echo $OldWorkflowID
+  #           export STACKS=$(aws cloudformation list-stacks \
+  #           --query "StackSummaries[*].StackName" \
+  #           --stack-status-filter CREATE_COMPLETE --no-paginate --output text)
+  #           echo Stack names: "${STACKS[@]}"
+  #     - run:
+  #         name: Remove old stacks and files
+  #         command: |
+  #           export OldWorkflowID=$(cat .circleci/files/OldWorkflowID.txt)
+  #           if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "${OldWorkflowID}" ]]
+  #           then
+  #             echo "--Delete confirmed--"
+  #             aws s3 rm "s3://$udapeople-{OldWorkflowID}" --recursive ||true
+  #             aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}" ||true
+  #             aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}" ||true
+  #           else
+  #             echo --------cannot remove stacks ---------
+  #           fi
 
 #   cloudfront-update:
 #     docker:
@@ -445,24 +472,7 @@ jobs:
 #             # your code here
 #       # Here's where you will add some code to rollback on failure  
 
-# cleanup:
-#     docker:
-#       # Docker image here
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Get old stack workflow id
-#           command: |
-#             # your code here
-#             export OldWorkflowID="the id here"
-#             export STACKS=[] #put the list of stacks here
-#       - run:
-#           name: Remove old stacks and files
-#           command: |
-#             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-#             then
-#               # your code here
-#             fi
+
             
 
 workflows:
